apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-hw-ingress
  annotations:
    kubernetes.io/ingress.class: haproxy-router
    haproxy.router.openshift.io/timeout: 5m
spec:
  rules:
    - host: argocdhelloworld.apps.aro-vpaas-dev.euw-hub02.azure.volvo.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-hw-service
                port:
                  number: 5000
  # Uncomment the following section if you have a TLS certificate
  tls:
    - hosts:
        - argocdhelloworld.apps.aro-vpaas-dev.euw-hub02.azure.volvo.net
      secretName: tls-cert  

